#!/bin/sh

DAEMON="aesdsocket"

start() {
	echo "Starting ${DAEMON}"
	start-stop-daemon -S -x "/usr/bin/$DAEMON" -- -d
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

stop() {
	echo "Stopping ${DAEMON}"
	start-stop-daemon -K -x "/usr/bin/$DAEMON"
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

case "$1" in
	start|stop)
		"$1";;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac
